import React from "react";
import { View, Text, Image, ScrollView, SafeAreaView } from "react-native";
import {
  BackgroundContainer,
  MainContainer,
  Header,
  HeaderTitle,
  BadgeContainer,
  BadgeImage,
  SectionTitle,
  SectionTitleText,
  AwardListContainer,
  AwardComponentContainer,
  AwardImage,
  AwardTitle,
  AwardTitleContainer,
} from "../style/styleAward";

const Award = () => {
  return (
    <>
      <BackgroundContainer source={require("../design/bg/AwardList_BG.png")} />
      <MainContainer>
        <Header>
          <HeaderTitle>AWARDS & BADGES</HeaderTitle>
        </Header>
        <BadgeContainer>
          <BadgeImage
            source={require("../design/ui/award/badges/badge_BLUE.png")}
          />
          <BadgeImage
            source={require("../design/ui/award/badges/badge_GREEN.png")}
          />
          <BadgeImage
            source={require("../design/ui/award/badges/badge_LPURPLE.png")}
          />
          <BadgeImage
            source={require("../design/ui/award/badges/badge_PURPLE.png")}
          />
        </BadgeContainer>
        <BadgeContainer>
          <BadgeImage
            source={require("../design/ui/award/badges/badge_RED.png")}
          />
          <BadgeImage
            source={require("../design/ui/award/badges/badge_TEAL.png")}
          />
          <BadgeImage
            source={require("../design/ui/award/badges/badge_WHITE.png")}
          />
          <BadgeImage
            source={require("../design/ui/award/badges/badge_YELLOW.png")}
          />
        </BadgeContainer>
        <SectionTitle>
          <SectionTitleText>AWARD HISTORY</SectionTitleText>
        </SectionTitle>
        <ScrollView>
          <AwardListContainer>
            <AwardComponentContainer>
              <AwardImage
                source={require("../design/ui/award/achievements/achievement_circle.png")}
              />
              <AwardTitleContainer>
                <AwardTitle>Award</AwardTitle>
              </AwardTitleContainer>
            </AwardComponentContainer>
            <AwardComponentContainer>
              <AwardImage
                source={require("../design/ui/award/achievements/achievement_circle.png")}
              />
              <AwardTitleContainer>
                <AwardTitle>Award</AwardTitle>
              </AwardTitleContainer>
            </AwardComponentContainer>
            <AwardComponentContainer>
              <AwardImage
                source={require("../design/ui/award/achievements/achievement_circle.png")}
              />
              <AwardTitleContainer>
                <AwardTitle>Award</AwardTitle>
              </AwardTitleContainer>
            </AwardComponentContainer>
            <AwardComponentContainer>
              <AwardImage
                source={require("../design/ui/award/achievements/achievement_circle.png")}
              />
              <AwardTitleContainer>
                <AwardTitle>Award</AwardTitle>
              </AwardTitleContainer>
            </AwardComponentContainer>
            <AwardComponentContainer>
              <AwardImage
                source={require("../design/ui/award/achievements/achievement_circle.png")}
              />
              <AwardTitleContainer>
                <AwardTitle>Award</AwardTitle>
              </AwardTitleContainer>
            </AwardComponentContainer>
            <AwardComponentContainer>
              <AwardImage
                source={require("../design/ui/award/achievements/achievement_circle.png")}
              />
              <AwardTitleContainer>
                <AwardTitle>Award</AwardTitle>
              </AwardTitleContainer>
            </AwardComponentContainer>
            <AwardComponentContainer>
              <AwardImage
                source={require("../design/ui/award/achievements/achievement_circle.png")}
              />
              <AwardTitleContainer>
                <AwardTitle>Award</AwardTitle>
              </AwardTitleContainer>
            </AwardComponentContainer>
            <AwardComponentContainer>
              <AwardImage
                source={require("../design/ui/award/achievements/achievement_circle.png")}
              />
              <AwardTitleContainer>
                <AwardTitle>Award</AwardTitle>
              </AwardTitleContainer>
            </AwardComponentContainer>
          </AwardListContainer>
        </ScrollView>
      </MainContainer>
    </>
  );
};

export default Award;
